[package]
name = "solfege-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
solfege-audio.workspace = true
solfege-core.workspace = true
solfege-engine = { workspace = true, features = ["fbmx"] }
solfege-event.workspace = true
solfege-osmp.workspace = true
solfege-model.workspace = true
solfege-storage.workspace = true
serde_json.workspace = true
fbmx-runtime = { workspace = true }

[[bin]]
name = "osmpc"
path = "src/main.rs"

[[bin]]
name = "solfege-render"
path = "src/bin/render.rs"

[[bin]]
name = "solfage-model"
path = "src/bin/model.rs"
